---
version: "2.1"
services:
  installer:
    image: nicholaswilde/keel:latest
    container_name: keel
    environment:
      - TZ=America/Los_Angeles #optional
      - PUID=1000   #optional
      - PGID=1000   #optional
    ports:
      - 9300:9300
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data:
